Statistics <- tabPanel(fluidRow(br(),
                                 column(3, 
                                        selectInput('var', 
                                                    'Choose your variable', 
                                                    choices = c('Matches',
                                                                'Goals_For', 
                                                                'Goals_Against',
                                                                'Goals_Diff',
                                                                'Wins',
                                                                'Draws',
                                                                'Losses',
                                                                'pct_wins',
                                                                'pct_draws',
                                                                'pct_losses'))),
                                 column(width = 3, offset = 3, 
                                        numericInput('teams', 
                                                     'Number of Teams', 
                                                     value = 10))),
                       fluidRow(column(9, 
                                       plotlyOutput('teste')
                       )),
                       title = 'Statistics')
