Statistics <- tabPanel(fluidRow(br(),
                                 column(3, 
                                        selectInput('var', 
                                                    'Choose your variable:', 
                                                    choices = c(`Matches` = 'Matches',
                                                                `Goals For` = 'Goals_For', 
                                                                `Goals Against` = 'Goals_Against',
                                                                `Goals Difference` = 'Goals_Diff',
                                                                `Wins` = 'Wins',
                                                                `Draws` = 'Draws',
                                                                `Losses` = 'Losses',
                                                                `% Wins`= 'pct_wins',
                                                                `% Draws`= 'pct_draws',
                                                                `% Losses`= 'pct_losses'))),
                                 column(width = 3, offset = 3, 
                                        numericInput('teams', 
                                                     'Number of Teams:', 
                                                     value = 10))),
                       fluidRow(column(9, 
                                       plotlyOutput('stats')
                       )),
                       fluidRow(column(3, 
                                       offset = 6,
                                       radioButtons('desc', 
                                                    'Teams ordered by:',
                                                    c('Descending order' = 'desc',                                                                                 '
                                                      Ascending order' = 'asc'),
                                                    selected = 'desc')
                                       )                   
                                ),
                       title = 'Statistics')
